<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use App\Models\Stand;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $stands = Stand::all();

        $vehicles = [
            // AutoGaragem Lisboa - Veículos económicos
            [
                'stand_id' => $stands->where('name', 'AutoGaragem Lisboa')->first()->id,
                'reference' => 'AGL001',
                'brand' => 'Renault',
                'model' => 'Clio',
                'year' => 2020,
                'mileage' => 45000,
                'fuel_type' => 'gasoline',
                'transmission' => 'manual',
                'engine_size' => 1.0,
                'power_hp' => 75,
                'doors' => 5,
                'seats' => 5,
                'color' => 'Branco',
                'price' => 12500.00,
                'original_price' => 13500.00,
                'discount_percentage' => 7.41,
                'description' => 'Renault Clio em excelente estado, único dono, revisões na marca. Ideal para cidade.',
                'features' => ['Ar condicionado', 'Direção assistida', 'ABS', 'Airbag', 'Rádio CD'],
                'status' => 'available',
                'is_featured' => true,
                'is_new' => false,
                'views_count' => 45,
            ],
            [
                'stand_id' => $stands->where('name', 'AutoGaragem Lisboa')->first()->id,
                'reference' => 'AGL002',
                'brand' => 'Peugeot',
                'model' => '208',
                'year' => 2019,
                'mileage' => 62000,
                'fuel_type' => 'diesel',
                'transmission' => 'manual',
                'engine_size' => 1.5,
                'power_hp' => 100,
                'doors' => 5,
                'seats' => 5,
                'color' => 'Azul',
                'price' => 14200.00,
                'original_price' => 15000.00,
                'discount_percentage' => 5.33,
                'description' => 'Peugeot 208 diesel, muito económico, ideal para viagens.',
                'features' => ['Ar condicionado', 'GPS', 'Bluetooth', 'Sensores de estacionamento'],
                'status' => 'available',
                'is_featured' => false,
                'is_new' => false,
                'views_count' => 23,
            ],
            [
                'stand_id' => $stands->where('name', 'AutoGaragem Lisboa')->first()->id,
                'reference' => 'AGL003',
                'brand' => 'Volkswagen',
                'model' => 'Golf',
                'year' => 2021,
                'mileage' => 28000,
                'fuel_type' => 'gasoline',
                'transmission' => 'automatic',
                'engine_size' => 1.5,
                'power_hp' => 150,
                'doors' => 5,
                'seats' => 5,
                'color' => 'Cinza',
                'price' => 22500.00,
                'original_price' => 24000.00,
                'discount_percentage' => 6.25,
                'description' => 'Volkswagen Golf seminovo, automático, muito confortável.',
                'features' => ['Ar condicionado', 'GPS', 'Câmera traseira', 'Sensores', 'Teto solar'],
                'status' => 'available',
                'is_featured' => true,
                'is_new' => false,
                'views_count' => 67,
            ],

            // CarStand Porto - Veículos médios
            [
                'stand_id' => $stands->where('name', 'CarStand Porto')->first()->id,
                'reference' => 'CSP001',
                'brand' => 'BMW',
                'model' => 'Série 3',
                'year' => 2020,
                'mileage' => 35000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'engine_size' => 2.0,
                'power_hp' => 190,
                'doors' => 4,
                'seats' => 5,
                'color' => 'Preto',
                'price' => 35000.00,
                'original_price' => 38000.00,
                'discount_percentage' => 7.89,
                'description' => 'BMW Série 3 em excelente estado, automático, muito confortável.',
                'features' => ['Ar condicionado', 'GPS', 'Couro', 'Sensores', 'Xenon'],
                'status' => 'available',
                'is_featured' => true,
                'is_new' => false,
                'views_count' => 89,
            ],
            [
                'stand_id' => $stands->where('name', 'CarStand Porto')->first()->id,
                'reference' => 'CSP002',
                'brand' => 'Mercedes',
                'model' => 'Classe C',
                'year' => 2019,
                'mileage' => 42000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'engine_size' => 2.1,
                'power_hp' => 170,
                'doors' => 4,
                'seats' => 5,
                'color' => 'Branco',
                'price' => 32000.00,
                'original_price' => 35000.00,
                'discount_percentage' => 8.57,
                'description' => 'Mercedes Classe C, elegante e confortável.',
                'features' => ['Ar condicionado', 'GPS', 'Couro', 'Sensores', 'LED'],
                'status' => 'available',
                'is_featured' => false,
                'is_new' => false,
                'views_count' => 34,
            ],

            // AutoMercado Braga - Veículos económicos
            [
                'stand_id' => $stands->where('name', 'AutoMercado Braga')->first()->id,
                'reference' => 'AMB001',
                'brand' => 'Fiat',
                'model' => 'Panda',
                'year' => 2018,
                'mileage' => 78000,
                'fuel_type' => 'gasoline',
                'transmission' => 'manual',
                'engine_size' => 1.2,
                'power_hp' => 69,
                'doors' => 5,
                'seats' => 5,
                'color' => 'Vermelho',
                'price' => 8500.00,
                'original_price' => 9500.00,
                'discount_percentage' => 10.53,
                'description' => 'Fiat Panda económico, ideal para cidade.',
                'features' => ['Ar condicionado', 'Direção assistida', 'ABS'],
                'status' => 'available',
                'is_featured' => false,
                'is_new' => false,
                'views_count' => 12,
            ],
            [
                'stand_id' => $stands->where('name', 'AutoMercado Braga')->first()->id,
                'reference' => 'AMB002',
                'brand' => 'Opel',
                'model' => 'Corsa',
                'year' => 2019,
                'mileage' => 55000,
                'fuel_type' => 'diesel',
                'transmission' => 'manual',
                'engine_size' => 1.3,
                'power_hp' => 95,
                'doors' => 5,
                'seats' => 5,
                'color' => 'Prata',
                'price' => 11500.00,
                'original_price' => 12500.00,
                'discount_percentage' => 8.00,
                'description' => 'Opel Corsa diesel, económico e fiável.',
                'features' => ['Ar condicionado', 'GPS', 'Bluetooth'],
                'status' => 'available',
                'is_featured' => true,
                'is_new' => false,
                'views_count' => 28,
            ],

            // LuxuryCars Coimbra - Veículos de luxo
            [
                'stand_id' => $stands->where('name', 'LuxuryCars Coimbra')->first()->id,
                'reference' => 'LCC001',
                'brand' => 'Audi',
                'model' => 'A6',
                'year' => 2021,
                'mileage' => 22000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'engine_size' => 3.0,
                'power_hp' => 286,
                'doors' => 4,
                'seats' => 5,
                'color' => 'Preto',
                'price' => 65000.00,
                'original_price' => 72000.00,
                'discount_percentage' => 9.72,
                'description' => 'Audi A6 de luxo, automático, muito confortável.',
                'features' => ['Ar condicionado', 'GPS', 'Couro', 'Sensores', 'Xenon', 'Teto solar'],
                'status' => 'available',
                'is_featured' => true,
                'is_new' => false,
                'views_count' => 156,
            ],
            [
                'stand_id' => $stands->where('name', 'LuxuryCars Coimbra')->first()->id,
                'reference' => 'LCC002',
                'brand' => 'BMW',
                'model' => 'Série 5',
                'year' => 2020,
                'mileage' => 28000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'engine_size' => 2.0,
                'power_hp' => 190,
                'doors' => 4,
                'seats' => 5,
                'color' => 'Azul',
                'price' => 58000.00,
                'original_price' => 65000.00,
                'discount_percentage' => 10.77,
                'description' => 'BMW Série 5, elegante e potente.',
                'features' => ['Ar condicionado', 'GPS', 'Couro', 'Sensores', 'LED'],
                'status' => 'available',
                'is_featured' => false,
                'is_new' => false,
                'views_count' => 78,
            ],

            // EcoVehicles Faro - Veículos elétricos/híbridos
            [
                'stand_id' => $stands->where('name', 'EcoVehicles Faro')->first()->id,
                'reference' => 'EVF001',
                'brand' => 'Tesla',
                'model' => 'Model 3',
                'year' => 2022,
                'mileage' => 15000,
                'fuel_type' => 'electric',
                'transmission' => 'automatic',
                'engine_size' => null,
                'power_hp' => 283,
                'doors' => 4,
                'seats' => 5,
                'color' => 'Branco',
                'price' => 45000.00,
                'original_price' => 48000.00,
                'discount_percentage' => 6.25,
                'description' => 'Tesla Model 3 elétrico, zero emissões, muito rápido.',
                'features' => ['Ar condicionado', 'GPS', 'Autopilot', 'Câmera 360°', 'Teto de vidro'],
                'status' => 'available',
                'is_featured' => true,
                'is_new' => false,
                'views_count' => 234,
            ],
            [
                'stand_id' => $stands->where('name', 'EcoVehicles Faro')->first()->id,
                'reference' => 'EVF002',
                'brand' => 'Toyota',
                'model' => 'Prius',
                'year' => 2021,
                'mileage' => 25000,
                'fuel_type' => 'hybrid',
                'transmission' => 'automatic',
                'engine_size' => 1.8,
                'power_hp' => 122,
                'doors' => 5,
                'seats' => 5,
                'color' => 'Prata',
                'price' => 28000.00,
                'original_price' => 30000.00,
                'discount_percentage' => 6.67,
                'description' => 'Toyota Prius híbrido, muito económico.',
                'features' => ['Ar condicionado', 'GPS', 'Sensores', 'Eco mode'],
                'status' => 'available',
                'is_featured' => false,
                'is_new' => false,
                'views_count' => 45,
            ],
        ];

        foreach ($vehicles as $vehicleData) {
            Vehicle::create($vehicleData);
        }

        $this->command->info('Veículos criados com sucesso!');
    }
}
